[features]
seeds = false
skip-lint = false
[programs.localnet]
solswap = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
solswap = "68TroHDJgubg8tGxKNpCe667nSGuyaksixHEEGaNY6nt"

[programs.mainnet]
solswap = "68TroHDJgubg8tGxKNpCe667nSGuyaksixHEEGaNY6nt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "tests/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
