[features]
seeds = false
skip-lint = false
[programs.localnet]
solswap = "BsHD57uBMbq3Xjfuhu5Cqa9FR8xrRKbxSPk8e7rw4pYY"

[programs.devnet]
solswap = "9fuV5utLoM5U81FQoiZLYB3moJzyJcV477cTpDYArmV1"

[programs.mainnet]
solswap = "9fuV5utLoM5U81FQoiZLYB3moJzyJcV477cTpDYArmV1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "tests/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solswap.ts"
