[features]
seeds = false
skip-lint = false
[programs.localnet]
solswap = "BsHD57uBMbq3Xjfuhu5Cqa9FR8xrRKbxSPk8e7rw4pYY"

[programs.devnet]
solswap = "BsHD57uBMbq3Xjfuhu5Cqa9FR8xrRKbxSPk8e7rw4pYY"

[programs.mainnet]
solswap = "BsHD57uBMbq3Xjfuhu5Cqa9FR8xrRKbxSPk8e7rw4pYY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "tests/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
